/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestiondestock;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ir Josue KAZIMOTO
 */
public class homePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(homePage.class.getName());

    /**
     * Creates new form homePage
     * @throws java.io.FileNotFoundException
     */
    
    public homePage() throws FileNotFoundException {
        initComponents();
        Rapport rap = new Rapport();
        mainPannel.add(rap);
//        mainPannel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPannel = new javax.swing.JPanel();
        navigation = new javax.swing.JMenuBar();
        menuProduits = new javax.swing.JMenu();
        menuRapport = new javax.swing.JMenuItem();
        menuProduit = new javax.swing.JMenuItem();
        menuGerer = new javax.swing.JMenuItem();
        menuVendre = new javax.swing.JMenuItem();
        menuRappVentes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Manager");
        setMaximumSize(new java.awt.Dimension(710, 500));
        setMinimumSize(new java.awt.Dimension(650, 400));
        setPreferredSize(new java.awt.Dimension(730, 500));

        mainPannel.setMaximumSize(new java.awt.Dimension(700, 500));
        mainPannel.setMinimumSize(new java.awt.Dimension(700, 500));
        mainPannel.setLayout(new java.awt.CardLayout());

        menuProduits.setText("Menus");
        menuProduits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProduitsActionPerformed(evt);
            }
        });

        menuRapport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        menuRapport.setText("Rapport");
        menuRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRapportActionPerformed(evt);
            }
        });
        menuProduits.add(menuRapport);

        menuProduit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        menuProduit.setText("Produit");
        menuProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProduitActionPerformed(evt);
            }
        });
        menuProduits.add(menuProduit);

        menuGerer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        menuGerer.setText("Gérer");
        menuGerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGererActionPerformed(evt);
            }
        });
        menuProduits.add(menuGerer);

        menuVendre.setText("Vendre");
        menuVendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendreActionPerformed(evt);
            }
        });
        menuProduits.add(menuVendre);

        menuRappVentes.setText("Rapport Ventes");
        menuRappVentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRappVentesActionPerformed(evt);
            }
        });
        menuProduits.add(menuRappVentes);

        navigation.add(menuProduits);

        setJMenuBar(navigation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProduitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProduitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProduitsActionPerformed

    private void menuProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProduitActionPerformed
        // TODO add your handling code here:
        Products p = new Products();
        mainPannel.removeAll();
        mainPannel.add(p);
        mainPannel.revalidate();
        mainPannel.repaint();
    }//GEN-LAST:event_menuProduitActionPerformed
    
    
    private void menuRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRapportActionPerformed
        try {
            // TODO add your handling code here:
            Rapport r = new Rapport();
            mainPannel.removeAll();
            mainPannel.add(r);
            mainPannel.revalidate();
            mainPannel.repaint();
        } catch (FileNotFoundException ex) {
            System.getLogger(homePage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_menuRapportActionPerformed

    private void menuGererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGererActionPerformed
        try {
            // TODO add your handling code here:
            gererExistant g = new gererExistant();
            mainPannel.removeAll();
            mainPannel.add(g);
            mainPannel.revalidate();
            mainPannel.repaint();
        } catch (FileNotFoundException ex) {
            System.getLogger(homePage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_menuGererActionPerformed

    private void menuVendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendreActionPerformed
        try {
            // TODO add your handling code here:
            VendreProduit v = new VendreProduit();
            mainPannel.removeAll();
            mainPannel.add(v);
            mainPannel.revalidate();
            mainPannel.repaint();
        } catch (IOException ex) {
            System.getLogger(homePage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_menuVendreActionPerformed

    private void menuRappVentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRappVentesActionPerformed
        // TODO add your handling code here:
        rapportVentes rpv = new rapportVentes();
        mainPannel.removeAll();
        mainPannel.add(rpv);
        mainPannel.revalidate();
        mainPannel.repaint();
    }//GEN-LAST:event_menuRappVentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        // Creation du fichier de stock existant s'il n'existe pas
        File dataFile = new File("stock.csv");
        if (!dataFile.exists()) {
            try {
            // Création du fichier et éventuellement de l'en-tête CSV
            if (dataFile.createNewFile()) {
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(dataFile, true))) {
                    bw.write("ID,Nom,Quantité,Prix Unitaire,Prix Total\n");
                }
            }
            } catch (IOException ex) {
            }
        }
        //Creation du fichier des stock vendus
        File ventesFile = new File("stockVendus.csv");
        if (!ventesFile.exists()) {
            try {
            // Création du fichier et éventuellement de l'en-tête CSV
            if (ventesFile.createNewFile()) {
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(ventesFile, true))) {
                    bw.write("Date,ID,Nom,Quantité,Prix Unitaire,Prix Total\n");
                }
            }
            } catch (IOException ex) {
            }
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new homePage().setVisible(true);
            } catch (FileNotFoundException ex) {
                System.getLogger(homePage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPannel;
    private javax.swing.JMenuItem menuGerer;
    private javax.swing.JMenuItem menuProduit;
    private javax.swing.JMenu menuProduits;
    private javax.swing.JMenuItem menuRappVentes;
    private javax.swing.JMenuItem menuRapport;
    private javax.swing.JMenuItem menuVendre;
    private javax.swing.JMenuBar navigation;
    // End of variables declaration//GEN-END:variables
    
}
