/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestiondestock;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ir Josue KAZIMOTO
 */
public class rapportVentes extends javax.swing.JPanel {

    /**
     * Creates new form rapportVentes
     */
    File ventesFile = new File("stockVendus.csv");

    public void chargerProduitsDansJTable() {
        DefaultTableModel model = (DefaultTableModel) tableDonnees.getModel();
        model.setRowCount(0); // Efface les anciennes lignes du tableau

        try (BufferedReader br = new BufferedReader(new FileReader(ventesFile))) {
            String ligne;
            while ((ligne = br.readLine()) != null) {
                if (ligne.startsWith("Date") || ligne.trim().isEmpty()) continue; // ignorer l'entête
                    String[] donnees = ligne.split(",");
                if (donnees.length >= 6) {
                    model.addRow(new Object[]{donnees[0], donnees[1], donnees[2], donnees[3], donnees[4],donnees[5]});
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, 
                    "Erreur de lecture du fichier stockVendus.csv", 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public rapportVentes() {
        initComponents();
        // Parametrage de la date 
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE dd/MM/yyyy", new Locale("fr","FR"));
        String dateFormatee = sdf.format(date);
        String dateF;
        dateF = dateFormatee.substring(0, 1).toUpperCase() + dateFormatee.substring(1);
        lblDate.setText(dateF);
        
        //        La table
        int HEIGHT =30;
        tableDonnees.setRowHeight(HEIGHT);
        chargerProduitsDansJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDonnees = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblTitle.setText("Company.co");

        lblDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate.setMaximumSize(new java.awt.Dimension(600, 400));
        lblDate.setMinimumSize(new java.awt.Dimension(600, 400));
        lblDate.setPreferredSize(new java.awt.Dimension(600, 400));

        tableDonnees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableDonnees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "ID", "Nom Produit", "Quantite", "Prix Unitaire", "Prix Tot"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDonnees.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tableDonnees.setShowGrid(true);
        tableDonnees.setSurrendersFocusOnKeystroke(true);
        tableDonnees.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableDonnees);
        if (tableDonnees.getColumnModel().getColumnCount() > 0) {
            tableDonnees.getColumnModel().getColumn(1).setMinWidth(70);
            tableDonnees.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ventes effectuées");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tableDonnees;
    // End of variables declaration//GEN-END:variables
}
